url: rdm.elixir-belgium.org
repository: ELIXIR-Belgium/rdm-guide

topnav_title: RDM Guide
# this appears on the top navigation bar next to the home button

site_title: RDM Guide
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: ELIXIR Belgium
# this appears in the page_ending

# github_editme_path: 
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

description: "RDM Guide is an information resource about research data management for biologists and scientists in Life Sciences, curated by ELIXIR Belgium."
# Metadata description of the website

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

gtag: G-3R26BTQ30X
# Google analytics tag

exclude:
  - .gitignore
  - README.md

# feedback_subject_line: 

# contact_email: rdm-editors@elixir-europe.org
# used as a contact email for the Feedback link in the top navigation bar

feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Give feedback"
# if you uncomment the previous line, it changes the Feedback text

markdown: kramdown
highlighter: rouge
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename:output_ext
      layout: "page"
      comments: false
      search: true
      sidebar: main
      topnav: topnav

plugins:
  - jemoji
